consultas/urls.py
from django.urls import path
from .views import historial_pacientes,buscar_paciente_si_existe, info_paciente, nuevo_paciente,agregar_consulta,imprimir_pdf_receta,ver_ficha_paciente
from core.views import HomePageView

consultas_patterns = ([
    path('', HomePageView.as_view(), name='mhome'),
    path('buscar_paciente/', buscar_paciente_si_existe, name='buscar_paciente'),
    path('paciente/<int:pk>', info_paciente, name='info_paciente'),
    path('npaciente/',nuevo_paciente, name='nuevo_paciente'),
    path('agregar_consulta/<int:pk>',agregar_consulta, name='realizar_consulta'),
    path('ficha_paciente/<int:pk>',ver_ficha_paciente,name='ficha'),
    path('imprimir/<int:pk>',imprimir_pdf_receta,name='imprimir'),
    path('historial_pacientes/',historial_pacientes,name='historial_p')
],'consultas')

core/urls.py
from django.urls import path, include

from .views import HomePageView, InicioPageView


urlpatterns = [
    path('', InicioPageView.as_view(), name="inicio"),
    path('club/', HomePageView.as_view(), name="home"),
    
]

zMedicalWeedApp/urls.py
from django.contrib import admin
from django.urls import path, include
from noticias.urls import noticias_patterns
from miembros.urls import miembros_patterns
from productos.urls import productos_patterns
from eventos.urls import eventos_patterns
from clubes.urls import clubes_patterns
from consultas.urls import consultas_patterns
from horarios.urls import horarios_patterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    #Path Home
    path('', include("core.urls")),

    #Path de clubes
    path('clubes/', include(clubes_patterns)),

    #Path de noticias
    path('club/noticias/',include(noticias_patterns)),

    #Path de miembros
    
    path('club/miembros/', include(miembros_patterns)),

    #Path de productos
    path('club/productos/', include(productos_patterns)),

    #Path de eventos
    path('club/eventos/', include(eventos_patterns)),

    #Path de consultas
    path('medico/', include(consultas_patterns)),

    #Path de horarios medicos
    path('medico/horarios/', include(horarios_patterns)),

    #Path del auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]


#Media
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

consultas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Paciente(models.Model):
    rut = models.CharField(max_length=10, verbose_name = "Rut")
    nombres = models.CharField(max_length=40, verbose_name = "Nombres")
    apellido_p = models.CharField(max_length=20, verbose_name = "Apellido paterno")
    apellido_m = models.CharField(max_length=20, verbose_name = "Apellido materno")
    fecha_nacimiento = models.DateField(verbose_name="Fecha de nacimiento")
    correo = models.CharField(max_length=100, verbose_name = "Correo electronico")
    celular = models.CharField(max_length=12, verbose_name = "Numero celular")
    direccion = models.CharField(max_length=200, verbose_name = "Direccion")
    genero = models.CharField(max_length=1, verbose_name = "Genero")
    user = models.ForeignKey(User,verbose_name = "Cuenta de usuario", on_delete=models.CASCADE, default=200)
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de creacion")
    updated = models.DateTimeField(auto_now = True, verbose_name = "Fecha de ult. actualizacion")

class Consulta(models.Model):
    paciente = models.ForeignKey(Paciente,verbose_name ="Paciente atendido",on_delete=models.CASCADE)
    medico = models.ForeignKey(User,verbose_name="Medico",on_delete=models.CASCADE)
    anotaciones = models.TextField(verbose_name="Datos de la consulta")
    diagnostico = models.TextField(verbose_name="Diagnostico")
    prescripcion = models.TextField(verbose_name="Prescripcion")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de creacion")
    updated = models.DateTimeField(auto_now = True, verbose_name = "Fecha de ult. actualizacion")

consultas/forms.py
from django import forms
from .models import Paciente,Consulta
from itertools import cycle
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from registration.models import Profile


class AgregarConsulta(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = ['paciente','medico','anotaciones','diagnostico','prescripcion']
        widgets = {
            'paciente':forms.HiddenInput(),
            'medico':forms.HiddenInput(),
            'anotaciones':forms.Textarea(attrs={'class':'form-control mb-2',}),
            'diagnostico':forms.Textarea(attrs={'class':'form-control mb-2',}),
            'prescripcion':forms.Textarea(attrs={'class':'form-control mb-2',}),
        }

class BuscarPaciente(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['rut']
        widgets = {
            'rut':forms.TextInput(attrs={'class':'form-control mb-2'}),
        }

class InfoPaciente(forms.ModelForm):
    class Meta:
        model = Paciente
        GENERO=[
            ('M','Masculino'),
            ('F','Femenino'),
        ]

        fields = ['rut','nombres','apellido_p','apellido_m','fecha_nacimiento',
        'correo','celular','direccion','genero','user']
        
        widgets = {
            'rut':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: 11111111-1'}),
            'nombres':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: Jorge'}),
            'apellido_p':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: Salinas'}),
            'apellido_m':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: Fuentes'}),
            'fecha_nacimiento':forms.DateInput(attrs={'class':'form-control mb-2','placeholder':'Ej: DD/MM/AAAA','readonly':'true'}),
            'correo':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: correo_ejemplo@ejemplo.com'}),
            'celular':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: +56967878678'}),
            'direccion':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: Avda. Vicuña Mackena 1010'}),
            'genero':forms.RadioSelect(attrs = {'class':'form-check-input'},choices=GENERO),
            'user':forms.HiddenInput()
        }
        labels = {
            'rut':'Rut' ,
            'nombres':'Nombre',
            'apellido_p':'Apellido paterno',
            'apellido_m':'Apellido materno',
            'fecha_nacimiento':'Fecha de nacimiento',
            'correo':'Correo electronico',
            'celular':'Numero celular',
            'direccion':'Direccion',
            'genero':'Género',
        }

    


class NuevoPaciente(forms.ModelForm):
    class Meta:
        model = Paciente
        GENERO=[
            ('M','Masculino'),
            ('F','Femenino'),
        ]

        fields = ['rut','nombres','apellido_p','apellido_m','fecha_nacimiento',
        'correo','celular','direccion','genero','user']
        
        widgets = {
            'rut':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: 11111111-1'}),
            'nombres':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: Jorge'}),
            'apellido_p':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: Salinas'}),
            'apellido_m':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: Fuentes'}),
            'fecha_nacimiento':forms.DateInput(attrs={'class':'form-control mb-2','placeholder':'Ej: DD/MM/AAAA'}),
            'correo':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: correo_ejemplo@ejemplo.com'}),
            'celular':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: +56967878678'}),
            'direccion':forms.TextInput(attrs={'class':'form-control mb-2','placeholder':'Ej: Avda. Vicuña Mackena 1010'}),
            'genero':forms.RadioSelect(attrs = {'class':'form-check-input'},choices=GENERO),
            'user':forms.HiddenInput()
        }
        labels = {
            'rut':'Rut' ,
            'nombres':'Nombre',
            'apellido_p':'Apellido paterno',
            'apellido_m':'Apellido materno',
            'fecha_nacimiento':'Fecha de nacimiento',
            'correo':'Correo electronico',
            'celular':'Numero celular',
            'direccion':'Direccion',
            'genero':'Género',
        }



    def clean_rut(self):
        rut = self.cleaned_data['rut']
        profiles = Profile.objects.all()
        
        rut = rut.upper()
        rut = rut.replace("-","")
        rut = rut.replace(".","")
        aux = rut[:-1]
        dv = rut[-1:]
    
        revertido = map(int, reversed(str(aux)))
        factors = cycle(range(2,8))
        s = sum(d * f for d, f in zip(revertido,factors))
        res = (-s)%11
    
        if str(res) == dv:
            pass
        elif dv=="K" and res==10:
            pass
        else:
            
            raise ValidationError("El rut ingresado no es válido")

        for profile in profiles:
            if profile.rut == rut:
                raise ValidationError("El rut ingresado ya esta registrado")
                break
        return rut

consultas/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.models import User
from .forms import BuscarPaciente,InfoPaciente,NuevoPaciente,AgregarConsulta
from .models import Paciente, Consulta
from registration.models import Profile
#Imprimir PDF
import io
from django.http import FileResponse, HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4



def buscar_paciente_si_existe(request):
    #Buscaremos si el paciente ya tiene cuenta en mwa, en caso de si tener cuenta redireccionamos a un
    #modificar que permita ver los datos actuales del paciente, si tiene todos sus datos se mostraran
    #solo readonly, en caso de faltar alguno esos se podran colocar y los que ya esten readonly
    if request.method == 'POST':
        usuarios = User.objects.all()
        form = BuscarPaciente(request.POST)
        print("Hasta aca todo bien")
        for usuario in usuarios:

            if usuario.profile.tipo_cuenta_id == 1:

                print("usuario {} request {}".format(usuario.username,request.POST['rut']))
                if usuario.username == request.POST['rut']:
                    print("Paciente ya tiene una cuenta")
                    return redirect('consultas:info_paciente', pk=usuario.id)
                    #Aca redireccionamos y salimos de la funcion
        #Aca el paciente no tendria cuenta procederiamos a tomar sus datos para posteriormente crearle una
        print("Paciente no tiene cuenta")
        #Aca redireccionamos y salimos de la funcion
        return redirect('consultas:nuevo_paciente')
    else:
        form = BuscarPaciente()
        ctx = {'form':form}
        return render(request,'consultas/buscar_paciente.html',ctx)


def info_paciente(request,pk):
    p = get_object_or_404(User,pk=pk)
    profiles = Profile.objects.all()
    print("paciente {}".format( p.username))
    for profile in profiles:
        if profile.user_id == p.id:
            print("Victoriaaaa")
            form = InfoPaciente(instance=profile)
            rut = profile.rut
            nombres = profile.nombres
            apellido_p = profile.apellido_p
            apellido_m = profile.apellido_m
            fecha_nacimiento = profile.fecha_nacimiento
            user = profile.user_id
            break
        else:
            form = InfoPaciente()

    if request.method=='POST':

        form = InfoPaciente(request.POST,instance=profile)
        request.POST._mutable=True
        request.POST['rut'] = rut
        request.POST['nombres'] = nombres
        request.POST['apellido_p'] = apellido_p
        request.POST['apellido_m'] = apellido_m
        request.POST['fecha_nacimiento'] = fecha_nacimiento
        request.POST['fecha_nacimiento'] = fecha_nacimiento
        request.POST['user'] = user
        if form.is_valid():
            print("Validisimo viejo")
            form.save()
            return redirect('consultas:realizar_consulta',pk=user)
        else:
            print('NO FUE VALIDO PQ {}'.format(form.errors))
    ctx={'form':form,'pk':pk}
    return render(request,'consultas/datos_paciente.html',ctx)
    #Para que esto funcione necesitaremos que profile tenga los datos de persona.


def nuevo_paciente(request):
    if request.method == 'POST':
        form = NuevoPaciente(request.POST)
        request.POST._mutable = True
        request.POST['user'] = 14
        if form.is_valid():
            print("Formulario valido")
            form.save()
            return redirect('consultas:realizar_consulta',pk=user)#configurar url
        else:
            print('NO FUE VALIDO PQ {}'.format(form.errors))
    else:
        form = NuevoPaciente()
    ctx = {'form':form}
    return render(request,'consultas/nuevo_paciente.html',ctx)


def agregar_consulta(request,pk):
    user_paciente = get_object_or_404(User, pk=pk)
    id_paciente  = get_object_or_404(Paciente,user=pk)
    # id_paciente = Paciente.objects.get(user=pk)
    if request.method == 'POST':
        form = AgregarConsulta(request.POST)
        request.POST._mutable= True
        request.POST['paciente']=id_paciente.id
        request.POST['medico']=request.user.id
        if form.is_valid():
            form.save()
            return redirect('consultas:ficha',pk=id_paciente.id)
        else:
            print(form.errors)
    else:
        form = AgregarConsulta()
    ctx={'form':form,'pk':pk}
    return render(request,'consultas/registrar_consulta.html',ctx)

def ver_ficha_paciente(request,pk):
    paciente = get_object_or_404(Paciente,pk=pk)
    consultas = Consulta.objects.all()
    if request.method == 'POST':
        if '_imprimir' in request.POST:
            c = Consulta.objects.raw('''select * from consultas_consulta where medico_id = 16
                                            order by created DESC limit 1''')[0]
            pk=c.id
            return redirect('consultas:imprimir',pk=pk)
            
        elif '_volver' in request.POST:
            return redirect('consultas:buscar_paciente')
    ctx={
        'pk':pk,
        'paciente':paciente,
        'consultas':consultas,
    }
    return render(request,'consultas/ficha_paciente.html',ctx)


def imprimir_pdf_receta(request,pk):
    consulta = get_object_or_404(Consulta,pk=pk)
    medico = get_object_or_404(User,pk=consulta.medico_id)

    response=HttpResponse(content_type='application/pdf')
    response['Content-Disposition']='attachement; filename=receta_med.pdf'
     # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()
    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer,pagesize=A4)

    p.setLineWidth(.3)
    p.setFont('Helvetica',22)
    p.drawString(30,750,'Receta Medica')
    p.setFont('Helvetica',12)
    p.drawString(30,735,medico.username)


    fecha = consulta.created
    fecha_f = fecha.strftime('%d/ %m/ %Y')
    p.setFont('Helvetica-Bold',12)
    p.drawString(480,750,fecha_f)
    p.line(460,747,560,747)
    
    
    p.save()
    pdf=buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response

def historial_pacientes(request):
 
    pacientes = Consulta.objects.raw('''select MAX(c.created) as fecha,c.id,p.id, p.nombres, p.apellido_p, 
                                        p.apellido_m, p.rut from consultas_paciente p 
                                        inner join consultas_consulta c 
                                        where c.paciente_id = p.id group by p.rut;''')
    ctx={'pacientes':pacientes,}
    return render(request,'consultas/historial_pacientes.html',ctx)

consultas/templates/consultas/buscar_paciente.html
{% extends 'core/base_layout_medico.html' %}

{% block title %}Registrar consulta{% endblock %}
{% block content %}


    <form class="form-inline" method='post' action="" style='heigth:50px;'>{% csrf_token %}
        <div class="input-group mb-3 ml-4">
            <input style='width:350px;'type="text" id="id_rut" value="" name='rut' class="form-control" placeholder="Ingrese el rut del paciente, sin puntos ni guión." >
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit" >Buscar</button>
            </div>
        </div>
    </form>

{% endblock %}

consultas/templates/consultas/datos_paciente.html
{% extends 'core/base_layout_medico.html' %}
{% block title %}Paciente{% endblock %}
{% comment %} Aca se debera diferenciar entre nuevo paciente y antigo pa cambiar el title en un if {% endcomment %}

{% block content %}

<main role="main">
  <div class="container">
        <form action="" method="post" class="form-sample" enctype=multipart/form-data>{% csrf_token %}
          <div class="col-12 ">
              <div class="card mt-2" style="width:130%">
                <div class="card-body">
                  <h4 class="card-title">Argegar nuevo paciente</h4>
                    <p class="card-description">
                      Información del paciente
                    </p>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">{{form.rut.label_tag}}</label>
                          <div class="col-sm-9">
                            {% comment %} {{form.rut}} {% endcomment %}
                            <input readonly id='id_rut' name='rut' class='form-control mb-2' placeholder ='Ej: 11111111-1' value={{form.rut.value}}>
                            {% if form.rut.errors %}
                              <ul>
                                {%for error in form.rut.errors%}
                                  <li style="list-style:none;" class="text-danger">{{form.rut.errors}}</li>
                                {%endfor%}
                              </ul>
                            {%endif%}
                            
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">{{form.nombres.label_tag}}</label>
                          <div class="col-sm-9">
                            <input readonly id='id_nombres' name='nombres' class='form-control mb-2' placeholder ='Ej: 11111111-1' value={{form.nombres.value}}>
                            {% if form.nombres.errors %}
                              <ul>
                                {%for error in form.nombres.errors%}
                                  <li style="list-style:none;" class="text-danger">{{form.nombres.errors}}</li>
                                {%endfor%}
                              </ul>
                            {%endif%}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Apellido paterno</label>
                          <div class="col-sm-9">
                            <input readonly id='id_apellido_p' name='apellido_p' class='form-control mb-2' placeholder ='Ej: 11111111-1' value={{form.apellido_p.value}}>
                            {% if form.apellido_p.errors %}
                              <ul>
                                {%for error in form.apellido_p.errors%}
                                  <li style="list-style:none;" class="text-danger">{{form.apellido_p.errors}}</li>
                                {%endfor%}
                              </ul>
                            {%endif%}
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Apellido materno</label>
                          <div class="col-sm-9">
                            <input readonly id='id_apellido_m' name='apellido_m' class='form-control mb-2' placeholder ='Ej: 11111111-1' value={{form.apellido_m.value}}>
                            {% if form.apellido_m.errors %}
                              <ul>
                                {%for error in form.apellido_m.errors%}
                                  <li style="list-style:none;" class="text-danger">{{form.apellido_m.errors}}</li>
                                {%endfor%}
                              </ul>
                            {%endif%}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Fecha de nacimiento</label>
                          <div class="col-sm-9">
                            {{form.fecha_nacimiento}}
                            {% if form.fecha_nacimiento.errors %}
                              <ul>
                                {%for error in form.fecha_nacimiento.errors%}
                                  <li style="list-style:none;" class="text-danger">{{form.fecha_nacimiento.errors}}</li>
                                {%endfor%}
                              </ul>
                            {%endif%}
                          </div>
                        </div>
                      </div>
 
                      
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Género</label>
                          <div class="col-sm-9">
                            {{form.genero}}
                            {% if form.genero.errors %}
                              <ul>
                                {%for error in form.genero.errors%}
                                  <li style="list-style:none;" class="text-danger">{{form.genero.errors}}</li>
                                {%endfor%}
                              </ul>
                            {%endif%}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Celular</label>
                          <div class="col-sm-9">
                            {{form.celular}}
                            {% if form.celular.errors %}
                              <ul>
                                {%for error in form.celular.errors%}
                                  <li style="list-style:none;" class="text-danger">{{form.celular.errors}}</li>
                                {%endfor%}
                              </ul>
                            {%endif%}
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Dirección</label>
                          <div class="col-sm-9">
                            {{form.direccion}}
                            {% if form.direccion.errors %}
                              <ul>
                                {%for error in form.direccion.errors%}
                                  <li style="list-style:none;" class="text-danger">{{form.direccion.errors}}</li>
                                {%endfor%}
                              </ul>
                            {%endif%}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class='row'>
                    <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Correo electronico</label>
                          <div class="col-sm-9">
                            {{form.correo}}
                            {% if form.correo.errors %}
                              <ul>
                                {%for error in form.correo.errors%}
                                  <li style="list-style:none;" class="text-danger">{{form.correo.errors}}</li>
                                {%endfor%}
                              </ul>
                            {%endif%}
                          </div>
                        </div>
                      </div>  
                      {{form.user_id}}
                      <div class="col-md-6">
                        <div class = "text-center">
                      <input type="submit" class="btn btn-primary " value="Siguiente" style="width:120px;"/>
                      <a class="btn btn-inverse-secondary  btn-fw" style="width:120px;" href="{% url 'consultas:buscar_paciente' %}">Volver</a>
                    </div>
                      </div>
                    </div>
                </div>
              </div>
            </div>
        </form>
      </div>
</main>

{% endblock %}

consultas/templates/consultas/ficha_paciente.html
{% extends 'core/base_layout_medico.html' %}
{% block title %}Paciente{% endblock %}
{% load static %}
{% block content %}
<form method='POST' class="form-sample" action="">{% csrf_token %}
<div class="card mb-3 ml-2" style="width:600px;">
  <img src="{% static '/consultas/img/ficha_paciente.jpg' %}" class="card-img-top" alt="..." width="450" height="250" > 
  {% comment %} Arreglar ancho de la foto, esta srea solo decorativa asique buscar foto {% endcomment %}
  <div class="card-body">
    <h5 class="card-title">{{paciente.apellido_p}} {{paciente.apellido_m}}, {{paciente.nombres}}</h5>
    <p class="card-text">Rut: {{paciente.rut}}</p>
    <p class="card-text">Fecha de nacimiento: {{paciente.fecha_nacimiento}}</p>
    <p class="card-text">Genero: {% if paciente.genero == 'M' %}Masculino{% else %}Femenino{% endif %}</p>
    <p class="card-text">Email: {{paciente.correo}}</p>
    <p class="card-text">N° Celular: {{paciente.celular}}</p>
    <p class="card-text">Dirección: {{paciente.direccion}}</p>
    <hr>
    <div style="margin-left:50px;">
    <button type="submit" class="btn btn-primary" name="_volver">Volver al menu principal</button>
    <button type="submit" class="btn btn-primary" name="_imprimir">Imprimir recta</button>
    </div>
  </div>
  <br>
  <h4 style="margin-left:20px;"><strong>Historial de consultas del paciente</strong></h4>
  <hr>
<table class="table table-sm" style="margin-left:10px; margin-right:20px;">
  <thead>
    <tr>
      <th scope="col">Apellidos</th>
      <th scope="col">Nombre</th>
      <th scope="col">Fecha consulta</th>
      <th scope="col">Acción</th>
    </tr>
  </thead>
  <tbody>
    {% for c in consultas %}
        {% if c.paciente_id == paciente.id %}
        <tr>
        <th>{{ paciente.apellido_p }} {{paciente.apellido_m}}</th>
        <td>{{paciente.nombres}}</td>
        <td>{{c.created}}</td>
        <td><a href="{% url 'consultas:imprimir' c.id %}"><img src="https://img.icons8.com/bubbles/50/000000/print.png"></a></td>
        </tr>
        {% endif %}
    {% endfor %}
  </tbody>
</table>

</div>
</form>
{% endblock %}

consultas/templates/consultas/historial_pacientes.html
{% extends 'core/base_layout_medico.html' %}
{% block title %}Paciente{% endblock %}
{% load static %}
{% block content %}
<div class="content mt-4 ml-4">
<h3>Pacientes atendidos</h3>
<br>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col"><strong>Rut</strong></th>
            <th scope="col"><strong>Apellidos</strong></th>
            <th scope="col"><strong>Nombre</strong></th>
            <th scope="col"><strong>Fecha ult. atencion</strong></th>
            <th scope="col"><strong>Acción</strong></th>
        </tr>
    </thead>
    <tbody>
    {% for p in pacientes %}
        {% if request.user.id == p.medico_id %}
            <tr>
                <td>{{p.rut}}</td>
                <th>{{p.apellido_p }} {{p.apellido_m}}</th>
                <td>{{p.nombres}}</td>
                <td>{{p.created}}</td>
                <td><img src="https://img.icons8.com/bubbles/50/000000/print.png"></td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

consultas/templates/consultas/registrar_consulta.html
{% extends 'core/base_layout_medico.html' %}
{% block title %}registrar consultas{% endblock %}

{% block content %}

<div class="container" style="width:900px;">
<form method='POST' class="form-sample" action="">{% csrf_token %}
  <div class="form-group">
    <label for="id_anotaciones">Anotaciones de la consutlta</label>
    <textarea class="form-control" name="anotaciones" id="id_anotaciones" rows="8"></textarea>
  </div>
  <div class="form-group">
    <label for="id_diagnostico">Diagnostico</label>
    <textarea class="form-control" name="diagnostico" id="id_diagnostico" rows="3"></textarea>
  </div>
  <div class="form-group">
    <label for="id_prescripcion">Prescripción</label>
    <textarea class="form-control" name="prescripcion" id="id_prescripcion" rows="5"></textarea>
  </div>
<div style="margin-left:300px;">
  <input type="submit" class="btn btn-primary " value="Guardar" style="width:120px;"/>
  <a class="btn btn-inverse-secondary  btn-fw" style="width:120px;" href="{% url 'consultas:buscar_paciente' %}">Volver</a>
</div>
</form>
</div>


{% endblock %}