core/urls.py
from django.urls import path, include

from .views import HomePageView, InicioPageView


urlpatterns = [
    path('', InicioPageView.as_view(), name="inicio"),
    path('club/', HomePageView.as_view(), name="home"),
    
]

productos/urls.py
from django.urls import path
from . import views
from .views import agregar_producto,estado_reservas,mis_reservas,ReservaListView ,ProductoListView, ProductoUpdateView, ProductoDeleteView, reservar_producto,ReservaListView

productos_patterns = ([
    path('', ProductoListView.as_view(), name='productos'),
    path('<int:pk>/', reservar_producto, name='producto'),
    path('create/', agregar_producto, name = 'create'),
    path('update/<int:pk>/', ProductoUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductoDeleteView.as_view(),name='delete'),
    path('reservas',ReservaListView.as_view(),name='reservas'),
    path('estado_reservas/<int:pk>/',estado_reservas,name='estado_reservas'),
    path('misreservas/', ReservaListView.as_view() ,name='mis_reservas')
],'productos')

zMedicalWeedApp/urls.py
from django.contrib import admin
from django.urls import path, include
from noticias.urls import noticias_patterns
from miembros.urls import miembros_patterns
from productos.urls import productos_patterns
from eventos.urls import eventos_patterns
from clubes.urls import clubes_patterns
from consultas.urls import consultas_patterns
from horarios.urls import horarios_patterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    #Path Home
    path('', include("core.urls")),

    #Path de clubes
    path('clubes/', include(clubes_patterns)),

    #Path de noticias
    path('club/noticias/',include(noticias_patterns)),

    #Path de miembros
    
    path('club/miembros/', include(miembros_patterns)),

    #Path de productos
    path('club/productos/', include(productos_patterns)),

    #Path de eventos
    path('club/eventos/', include(eventos_patterns)),

    #Path de consultas
    path('medico/', include(consultas_patterns)),

    #Path de horarios medicos
    path('medico/horarios/', include(horarios_patterns)),

    #Path del auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]


#Media
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

productos/models.py
from django.db import models
from clubes.models import Club
from django.contrib.auth.models import User


# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length=200,verbose_name="Producto")
    proporcion = models.CharField(max_length=200,verbose_name="Proporcion en % (Indica/Sativa/Rudelaris)")
    descripcion = models.TextField(verbose_name="Descripción")
    stock = models.SmallIntegerField(verbose_name="Stock disponible(Gramos)")
    precio_gramo = models.IntegerField(verbose_name = "Precio por gramo", default=8000)
    imagen = models.ImageField(verbose_name="Imagen", upload_to="productos")
    club_id = models.ForeignKey(Club, verbose_name = "Codigo de club",on_delete=models.CASCADE,default=1)
    created = models.DateTimeField(auto_now_add= True,verbose_name="Fecha de creacion")
    updated = models.DateTimeField(auto_now= True,verbose_name="Fecha de ult. actualizacion")

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ['updated', 'created']

    
    def __str__(self):
        return self.nombre

class Reserva(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.CASCADE,default=1,blank=True,null=True)
    usuario = models.ForeignKey(User,on_delete=models.CASCADE,default=1,blank=True,null=True)
    cantidad_reservar = models.SmallIntegerField(verbose_name="Cantidad a reservar")
    estado = models.CharField(max_length=1,verbose_name = "Estado",default='P')
    precio_total = models.IntegerField(verbose_name="Monto total de la reserva",default = 0)
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de creacion")
    updated = models.DateTimeField(auto_now = True, verbose_name = "Fecha de ult. actualizacion")

    class Meta:
        verbose_name = "Reserva"
        verbose_name_plural = "Reservas"
        ordering = ['-created']

    
    def __str__(self):
        return self.usuario

productos/forms.py
from django import forms
from .models import Producto, Reserva
from miembros.models import Miembro
from django.core.exceptions import ValidationError

class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ['nombre','proporcion','descripcion','stock','imagen','precio_gramo']
        widgets = {
            'nombre':forms.TextInput(attrs={'class':'form-control'}),
            'proporcion':forms.TextInput(attrs={'class':'form-control'}),
            'descripcion':forms.Textarea(attrs={'class':'form-control'}),
            'stock':forms.NumberInput(attrs={'class':'form-control'}),
            'imagen':forms.FileInput(attrs={'class':'form-control'}),
            'precio_gramo':forms.NumberInput(attrs={'class':'form-control'}),
        }
        labels = {
            'nombre':'Producto' ,
            'proporcion':'Proporciones',
            'descripcion':'Descripción del producto',
            'stock':'Stock disponible',
            'imagen':'Imagen',
            'precio_gramo':"Precio por gramo"
        }
    
    def clean_stock(self):
        stock = self.cleaned_data['stock']
        if stock <= 0:
            raise ValidationError("No se puede agregar un producto sin stock.")
        return stock
    
    def clean_precio_gramo(self):
        precio_gramo = self.cleaned_data['precio_gramo']
        if precio_gramo <= 0:
            raise ValidationError("El producto no puede tener un precio igual o menor a 0.")
        return precio_gramo

class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva

        ESTADO_OPCIONES=[
            ('P','Entrega pendiente'),
            ('E','Entregado'),
        ]

        fields = ['cantidad_reservar','estado','usuario','producto','precio_total']
        widgets = {
            'cantidad_reservar':forms.NumberInput(attrs={'class':'form-control'}),
            'estado':forms.HiddenInput(),
            'usuario':forms.HiddenInput(),
            'producto':forms.HiddenInput(),
            'precio_total':forms.HiddenInput(),
            
        }
    
    def clean_cantidad_reservar(self):
        cantidad = self.cleaned_data['cantidad_reservar']
        miembros = Miembro.objects.all()
        if cantidad <= 0:
            raise ValidationError("No puede reservar por 0 o menos.")
        else:
            pass
        return cantidad

    def clean(self):
        form_data = self.cleaned_data
        miembros = Miembro.objects.all()
        productos = Producto.objects.all()
        reservas = Reserva.objects.all()
        c = form_data['cantidad_reservar']
        user = form_data['usuario']
        for miembro in miembros:
            if user.id == miembro.user_id_id:
                cant = miembro.dosis_diaria * 14
                if c > cant:
                    self._errors['cantidad_reservar']="La cantidad que desea reservar supera el maximo permitido de dos semanas de dosis."
                    del form_data['cantidad_reservar']
                    break
                else:
                    for producto in productos:
                        if c > producto.stock:
                            self._errors['cantidad_reservar']="La cantidad que desea reservar supera el stock disponible."
                            del form_data['cantidad_reservar']
                            break
                        else:
                            for reserva in reservas:
                                if user == reserva.usuario:
                                    if reserva.estado == 'P':
                                        self._errors['cantidad_reservar']="No puede realizar la reserva, ya que aun tiene una reserva pendiente."
                                        del form_data['cantidad_reservar']
                                        break
            
        return form_data

class ListadoReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva

        fields = ['cantidad_reservar','estado','usuario','producto','precio_total']
        
        widgets = {
            'cantidad_reservar':forms.HiddenInput(attrs={'class':'form-control','readonly':True}),
            'estado':forms.HiddenInput(attrs={'class':'form-control','readonly':True}),
            'usuario':forms.HiddenInput(attrs={'class':'form-control','readonly':True}),
            'producto':forms.HiddenInput(attrs={'class':'form-control','readonly':True}),
            'precio_total':forms.HiddenInput(attrs={'class':'form-control','readonly':True}),
        }
         

productos/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from .forms import ProductoForm, ReservaForm, ListadoReservaForm
from .models import Producto, Reserva
from miembros.models import Miembro


# Create your views here.

class StaffRequiredMixin(object):
    """Este mixin requerira que el usuario sea miembro del staff"""
    @method_decorator(staff_member_required)
    def dispatch(self,request,*args,**kwargs):
        return super(StaffRequiredMixin,self).dispatch(request,*args,**kwargs)

class ProductoListView(ListView):
    model = Producto

# class ProductoDetailView(DetailView):
#     model = Producto

@method_decorator(staff_member_required,name='dispatch')
class ProductoCreateView(CreateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('productos:productos')

def agregar_producto(request):
    if request.method == "POST":
        form = ProductoForm(request.POST,request.FILES)
        print(form)
        if form.is_valid():
            form.save()
            return redirect("productos:productos")
    else:
        form = ProductoForm()
    return render(request,'productos/producto_form.html',{'form':form})    

@method_decorator(staff_member_required,name='dispatch')
class ProductoUpdateView(UpdateView):
    model = Producto
    form_class = ProductoForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('productos:update', args=[self.object.id])+'?ok'

@method_decorator(staff_member_required,name='dispatch')
class ProductoDeleteView(DeleteView):
    model = Producto
    success_url = reverse_lazy('productos:productos')

def reservar_producto(request,pk):
    producto = get_object_or_404(Producto,id=pk)
    miembros = Miembro.objects.all() #Se puede mejorar
    m={}
    cmax=0
    if request.method == "POST":
        print("Entro al post, {}".format(request.user))
        request.POST._mutable = True
        res = request.POST['cantidad_reservar']
        cant =  int(res) * producto.precio_gramo
        request.POST['precio_total'] = cant
        request.POST['usuario'] = request.user.id
        request.POST['producto'] = producto.id
        request.POST['estado'] = 'D'
        producto.stock = producto.stock - int(res)
        form = ReservaForm(request.POST)
        print(producto.precio_gramo)
        print(res)
        print(cant)
        if form.is_valid():            
            print("Formulario valido")
            form.save()
            producto.save()
            return redirect('productos:productos')
    else:
        print("Renderizando la pagina")
        
        form = ReservaForm()
        if request.user.profile.tipo_cuenta_id == 1:
            for miembro in miembros:
                if miembro.user_id_id == request.user.id:
                    
                    m = get_object_or_404(Miembro,pk=miembro.id)
                    cmax = m.dosis_diaria * 14
        else:
            m={}
            cmax = 0                
    contexto = {
        'form':form,'producto':producto,'m':m,'cmax':cmax
    }
    return render (request,'productos/producto_detail.html',contexto)

class ReservaListView(ListView):
    model = Reserva

def mis_reservas(request):
    return render(request,'productos/mis_reservas.html')
    
def estado_reservas(request, pk):
    reserva = get_object_or_404(Reserva,pk=pk)
    p = get_object_or_404(Producto,pk=reserva.producto_id)
    if request.method == "POST":
        request.POST._mutable = True
        request.POST['usuario'] = reserva.usuario_id
        request.POST['producto'] = reserva.producto_id
        request.POST['cantidad_reservar'] = reserva.cantidad_reservar
        request.POST['precio_total'] = reserva.precio_total
        res=request.POST['cantidad_reservar']
        if '_entregado' in request.POST:
            print("E")
            request.POST['estado'] = 'E'
        elif '_cancelar' in request.POST:
            print("C")
            request.POST['estado'] = 'C'
            p.stock = p.stock + int(res)
            print(request.POST['estado'])
        elif '_despachado' in request.POST:
            print("D")
            request.POST['estado'] = 'P'
        form = ListadoReservaForm(request.POST,instance=reserva)
        if form.is_valid():
            form.save()
            p.save()
            print(request.POST['estado'])
            return redirect('productos:reservas')
    else:
        form = ListadoReservaForm()
    return render(request, 'productos/reserva_detalle.html',{'form':form,'reserva':reserva})

    
            
            

productos/templates/productos/mis_reservas.html
{%extends 'core/base_layout_club.html'%}
{%block title%}Lista de reservas{%endblock%}
{%block content%}

              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Mis reservas</h4>
                  <p class="card-description">
                    Listado de reservas
                  </p>
                  <div class="table-responsive">
                    <table class="table table-hover table-striped table-bordered">
                      <thead class ="thead-dark">
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Miembro</th>
                          <th scope="col">Producto reservado</th>
                          <th scope="col">Cantidad reservada (gramos)</th>
                          <th scope="col">Precio Total</th>
                          <th scope="col">Estado de la reserva</th>
                          <th scope="col">Acción</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for reserva in reserva_list %}
                        {% if reserva.usuario == request.user %}
                            
                                <tr>
                                <th scope="row">{{reserva.id}}</th>
                                <td>{{reserva.usuario}}</td>
                                <td>{{reserva.producto.nombre}}</td>
                                <td>{{reserva.cantidad_reservar}}</td>
                                <td>{{reserva.precio_total}}</td>
                                <td>
                                {% if reserva.estado == 'P' %}
                                  <label class="badge badge-warning">Entrega Pendiente</label>
                                {% elif reserva.estado == 'E' %}
                                  <label class="badge badge-success">Entregado</label>
                                {% elif reserva.estado == 'C' %}
                                  <label class="badge badge-danger">Cancelado</label>
                                {% else %}
                                  <label class="badge badge-danger">Despachando reserva</label>
                                {% endif %}
                                </td>
                                <td>                
                                <a class="" href="{% url 'productos:estado_reservas' reserva.id %}" >🔎</a>
                                </td>
                                </tr>
                            
                        {% endif %}
                        {%endfor%}
                        </tbody>
                    </table>
                  </div>
                </div>
              </div>

{%endblock%}

productos/templates/productos/producto_confirm_delete.html
{% extends 'core/base_layout_club.html' %}
{% load static %}
{% block title %}Borrar producto{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres borrar <strong>"{{ object }}"</strong>?</p>
                <input type="submit" class="btn btn-primary btn-block" value="Sí, borrar el producto {{producto.nombre}}" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

productos/templates/productos/producto_detail.html
{% extends 'core/base_layout_club.html' %}
{% load static %}
{% block title %}{{producto.nombre}}{% endblock %}
{% block content %}
<form method='POST'>{% csrf_token %}
<div id="containerProducto">
          <div id="panel">
            <div class="col col-left">
                    <img src="{{producto.imagen.url}}" style="width:280px; height:325px;" >

            
            </div>
            <div class="col col-right">
              <div id="pop">
                <img id="close" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/523617/close_circle_button.svg" width="20px">
                <h3>{{producto.nombre}}</</h3>
                <p>
                  {{producto.descripcion|safe}}
                </p>
                <p>
                Disponible: {{producto.stock}} grs. / precio</p>
              </div>
              <div id="main">
                <h1>{{producto.nombre}}</h1>
                <div class="ratings">
                  <p>{{producto.club_id.nombre_org}} / {{producto.proporcion}}</p>
                </div>
                <div class="descrip">
                  <p>Descripcion</p><img id="info" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/523617/info_icon_light.svg" width="16px">
                </div>
                <div class="price">
                  <h2>${{producto.precio_gramo}}<span>/unidad</span></h2>
                </div>
                <div class="qty">
                  <h2>Cantidad</h2>

                  <img id="minus" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/523617/plus_minus-02.svg" width="30px" height="30px">
                  <input id="id_cantidad_reservar" name="cantidad_reservar" type="text" value=0 size=1>
                  <img id="plus" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/523617/plus_minus-01.svg" width="30px" height="30px">
                </div>
                <div class="add">
                  <input type="submit" value="Reservar">
                    {% if form.cantidad_reservar.errors %}
          <ul>
              <li style="list-style:none;" class="text-danger">{{form.cantidad_reservar.errors}}</li>
            
          </ul>
        {%endif%}
                </div>
                
              </div>
            </div>
          </div>
          </div>
</form>

{% endblock %}

productos/templates/productos/producto_form.html
{% extends 'core/base_layout_club.html' %}
{% load static %}
{% block title %}Agregar producto{% endblock %}
{% block content %}
<main role="main">
  <div class="col-md-12 stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Agregar nuevo producto.</h4>
        <p class="card-description">
          Información del producto.
        </p>
        <form action="" method="post" class="form-sample" enctype=multipart/form-data>{% csrf_token %}
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.nombre.label}}</label>
            <div class="col-sm-9">
              {{form.nombre}}
              {% if form.nombre.errors %}
                    <ul>
                      {%for error in form.nombre.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.nombre.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.proporcion.label}}</label>
            <div class="col-sm-9">
              {{form.proporcion}}
              {% if form.proporcion.errors %}
                    <ul>
                      {%for error in form.proporcion.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.proporcion.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.descripcion.label}}</label>
            <div class="col-sm-9">
              {{form.descripcion}}
              {% if form.descripcion.errors %}
                    <ul>
                      {%for error in form.descripcion.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.descripcion.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.stock.label}}</label>
            <div class="col-sm-9">
              {{form.stock}}
              {% if form.stock.errors %}
                    <ul>
                      {%for error in form.stock.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.stock.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.precio_gramo.label}}</label>
            <div class="col-sm-9">
              {{form.precio_gramo}}
              {% if form.precio_gramo.errors %}
                    <ul>
                      {%for error in form.precio_gramo.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.precio_gramo.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.imagen.label}}</label>
            <div class="col-sm-9">
              {{form.imagen}}
              {% if form.imagen.errors %}
                    <ul>
                      {%for error in form.imagen.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.imagen.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>

          {% comment %} {{form.as_p}} {% endcomment %}
          <button type="submit" class="btn btn-primary mr-2">Agregar producto</button>
        </form>
      </div>
    </div>
  </div> 
</main>
{% endblock %}

productos/templates/productos/producto_list.html
{% extends "core/base_layout_club.html" %}
{%block title%}Productos{%endblock%}
{%block content%}
    <section class="page-section about-heading">
      <div class="container">
      <tr>
        {% if request.user.is_staff %}
          <a class="btn btn-primary mt-3" href="{%url 'productos:create'%}" >Agregar Producto</a>
        {% endif %}
        
      </tr>
      <br/>
      
      <div class="bg-faded rounded p-5">
      <h2>Productos</h2>
        <ul class="list-unstyled">
          {%for producto in producto_list%}
            <li class="media">
              <img class="mr-3" src="{{producto.imagen.url}}" alt="Generic placeholder image" style="height:250px; width:200px;">
              <div class="media-body">
                <h5 class="mt-0 mb-1">{{producto.nombre}}</h5>
                {{producto.descripcion|safe}}<br>
                {{producto.club_id.nombre_org}}
                <strong>{{producto.proporcion}}<br></strong>
                <strong>Disponible: {{producto.stock}} gramos.</strong>
                <br>
            <a style="width:150px; height:40px;" class="btn btn-primary mt-1" href="{% url 'productos:producto' producto.id %}" >Leer más</a>
            
            {% if request.user.is_staff %}
            <a style="width:150px; height:40px;" class="btn btn-primary mt-1" href="{% url 'productos:update' producto.id %}" >Modificar</a>
            <a style="width:150px; height:40px;" class="btn btn-primary mt-1" href="{% url 'productos:delete' producto.id %}" >Eliminar</a>
            {% endif %}
              </div>
            
            </li><hr>
          {%endfor%}
        </ul>  
      </div>
      
      </div>
    </section>
{%endblock%}

productos/templates/productos/producto_update_form.html
{% extends 'core/base_layout_club.html' %}
{% load static %}
{% block title %}Modificar producto{% endblock %}
{% block content %}


            
 <main role="main">
  <div class="col-md-12 stretch-card mb-2 mt-2 ">
    <div class="card">
    {%if 'ok' in request.GET%}
              <p style="color: green;">El producto se ha actualizado correctamente
              <a href = "{% url 'productos:producto' producto.id  %}">Haz Click aqui para ver el resultado</a>
              </p>
            {%endif%}
      <div class="card-body">
        <h4 class="card-title">Modificar producto.</h4>
        <p class="card-description">
          Información del producto {{producto.nombre}}.
        </p>
        <form action="" method="post" class="form-sample" enctype=multipart/form-data>{% csrf_token %}
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.nombre.label}}</label>
            <div class="col-sm-9">
              {{form.nombre}}
              {% if form.nombre.errors %}
                    <ul>
                      {%for error in form.nombre.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.nombre.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.proporcion.label}}</label>
            <div class="col-sm-9">
              {{form.proporcion}}
              {% if form.proporcion.errors %}
                    <ul>
                      {%for error in form.proporcion.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.proporcion.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.descripcion.label}}</label>
            <div class="col-sm-9">
              {{form.descripcion}}
              {% if form.descripcion.errors %}
                    <ul>
                      {%for error in form.descripcion.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.descripcion.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.stock.label}}</label>
            <div class="col-sm-9">
              {{form.stock}}
              {% if form.stock.errors %}
                    <ul>
                      {%for error in form.stock.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.stock.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.precio_gramo.label}}</label>
            <div class="col-sm-9">
              {{form.precio_gramo}}
              {% if form.precio_gramo.errors %}
                    <ul>
                      {%for error in form.precio_gramo.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.precio_gramo.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-3 col-form-label">{{form.imagen.label}}</label>
            <div class="col-sm-9">
              {{form.imagen}}
              {% if form.imagen.errors %}
                    <ul>
                      {%for error in form.imagen.errors%}
                        <li style="list-style:none;" class="text-danger">{{form.imagen.errors}}</li>
                      {%endfor%}
                    </ul>
              {%endif%}
            </div>
          </div> 

          {% comment %} {{form.as_p}} {% endcomment %}
          <button type="submit" class="btn btn-primary mr-2">Modificar producto</button>
        </form>
      </div>
    </div>
  </div> 
</main>
{% endblock %}